/*
 * Author: Schlager Daniela
 * Class: 4BHIT
 * Date: 06.12.2019
 */


#ifndef SCHLAGER_UE2_LEDBLINKEN_FUNCTION_H
#define SCHLAGER_UE2_LEDBLINKEN_FUNCTION_H



#endif //SCHLAGER_UE2_LEDBLINKEN_FUNCTION_H
